### ISSUE TITLE
Review EmployeeDirective

### ISSUE THREAD

**Issue by mcacek** [objectpartners/angular2-timesheet#104]
I'm not entirely convinced that the EmployeeDirective is using the recommended approach. We're accessing the ElementRef directly and  I'm not sure that's appropriate for changing the content of a directive template. This also might be just fine.

**Comment by DSchau** [comment]
This is just fine, per [this link](https://angular.io/docs/ts/latest/guide/attribute-directives.html#!#write-the-directive-code)
