### ISSUE TITLE
Use an angular2 wrapper for the slides

### ISSUE THREAD

**Issue by DSchau** [objectpartners/angular2-timesheet#94]
Allows us to do some cool things, a la display actual Angular 2 components alongside Markdown (think: ComponentPlayground in the React world)

@mcacek

(I can probably do this; PR at some point in the future)

**Comment by mcacek** [comment]
I have an updated slide layout that we should consider migrating to. Unfortunately it is a Google slideshow but we should be able to translate the design.

**Comment by DSchau** [comment]
I've actually been working on this, it's pretty slick! It's an Angular 2 wrapper (so we can display any Angular code we want in the slide deck, i.e. by calling a component), and then I am working on an OPi theme, as well.

![screen shot 2017-03-03 at 10 00 15 am](https://cloud.githubusercontent.com/assets/3924690/23558196/4a534730-fff8-11e6-8e25-d409348ba170.png)

**Comment by mcacek** [comment]
I like that a lot. I'm going to create a separate issue for the theme. We don't need to mix it in with this goodness.

**Comment by DSchau** [comment]
Good idea! You can see my current progress [here](https://github.com/DSchau/presentation-webpack-config) (it'd be nice to have an OPi private repo, but idk if we're limited on those or anything)

You can use it in an angular 2 webpack project like so:

## webpack.config.js

```javascript
const getWebpackConfig = require('opi-webpack-config');

const configFn = getWebpackConfig({}, {
  dirname: __dirname
});

module.exports = configFn;
```

**Comment by DSchau** [comment]
@mcacek can you make sure to @ me when you create the theme issue? I have some ideas.
