### ISSUE TITLE
Pull in the official Object Partners theme from the Google slideshow style

### ISSUE THREAD

**Issue by mcacek** [objectpartners/angular2-timesheet#95]

**Comment by DSchau** [comment]
@mcacek could you link to the Google spreadsheet? Not quite sure where it's at.

Here's where I've gotten it since last night (not perfect, but it's a start).

![slide-deck](https://cloud.githubusercontent.com/assets/3924690/23560393/e641ad1a-ffff-11e6-82b6-7de8f670fb09.png)

**Comment by mcacek** [comment]
https://docs.google.com/a/objectpartners.com/presentation/d/11ZCsDngu5ugWYgoGgSYIAn4_XhnUsqzN0Z4cuKiGyNk/edit?usp=sharing
